In [51]:
# Classification problem
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
df = sns.load_dataset("titanic")

In [53]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [54]:
# dropping same columns
df = df.drop(columns=['who','adult_male','alive','deck','class'])

In [55]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,S,Southampton,False
1,1,1,female,38.0,1,0,71.2833,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,S,Southampton,True
3,1,1,female,35.0,1,0,53.1000,S,Southampton,False
4,0,3,male,35.0,0,0,8.0500,S,Southampton,True

In [56]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
embark_town      2
alone            0
dtype: int64

In [57]:
df['embarked'].values

<ArrowStringArray>
['S', 'C', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'C',
 ...
 'S', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'C', 'Q']
Length: 891, dtype: str

In [58]:
df['embark_town'].values

<ArrowStringArray>
['Southampton',   'Cherbourg', 'Southampton', 'Southampton', 'Southampton',
  'Queenstown', 'Southampton', 'Southampton', 'Southampton',   'Cherbourg',
 ...
 'Southampton', 'Southampton', 'Southampton', 'Southampton',  'Queenstown',
 'Southampton', 'Southampton', 'Southampton',   'Cherbourg',  'Queenstown']
Length: 891, dtype: str

In [59]:
# dropping embarked
df = df.drop('embarked',axis=1)

In [60]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare  embark_town  alone
0         0       3    male  22.0      1      0   7.2500  Southampton  False
1         1       1  female  38.0      1      0  71.2833    Cherbourg  False
2         1       3  female  26.0      0      0   7.9250  Southampton   True
3         1       1  female  35.0      1      0  53.1000  Southampton  False
4         0       3    male  35.0      0      0   8.0500  Southampton   True

In [67]:
df['parch'].value_counts()

parch
0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: count, dtype: int64

In [62]:
df['embark_town'] = df['embark_town'].fillna('unknown')

In [63]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embark_town      0
alone            0
dtype: int64

In [64]:
df['age'] = df['age'].fillna(df['age'].mean())

In [65]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embark_town    0
alone          0
dtype: int64

In [68]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

In [69]:
le = LabelEncoder()

In [70]:
df['sex'] = le.fit_transform(df['sex'])

In [71]:
df['embark_town'] = le.fit_transform(df['embark_town'])

In [72]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embark_town  alone
0         0       3    1  22.0      1      0   7.2500            2  False
1         1       1    0  38.0      1      0  71.2833            0  False
2         1       3    0  26.0      0      0   7.9250            2   True
3         1       1    0  35.0      1      0  53.1000            2  False
4         0       3    1  35.0      0      0   8.0500            2   True

In [73]:
df['alone'] = le.fit_transform(df['alone'])

In [74]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embark_town  alone
0         0       3    1  22.0      1      0   7.2500            2      0
1         1       1    0  38.0      1      0  71.2833            0      0
2         1       3    0  26.0      0      0   7.9250            2      1
3         1       1    0  35.0      1      0  53.1000            2      0
4         0       3    1  35.0      0      0   8.0500            2      1

In [76]:
# train_test_split
from sklearn.model_selection import train_test_split
X = df.drop('survived',axis=1)
y = df['survived']

In [77]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

In [78]:
X_train

     pclass  sex        age  sibsp  parch      fare  embark_town  alone
331       1    1  45.500000      0      0   28.5000            2      1
733       2    1  23.000000      0      0   13.0000            2      1
382       3    1  32.000000      0      0    7.9250            2      1
704       3    1  26.000000      1      0    7.8542            2      0
813       3    0   6.000000      4      2   31.2750            2      0
..      ...  ...        ...    ...    ...       ...          ...    ...
106       3    0  21.000000      0      0    7.6500            2      1
270       1    1  29.699118      0      0   31.0000            2      1
860       3    1  41.000000      2      0   14.1083            2      0
435       1    0  14.000000      1      2  120.0000            2      0
102       1    1  21.000000      0      1   77.2875            2      0

[712 rows x 8 columns]

In [79]:
print(X_train.shape,X_test.shape)

(712, 8) (179, 8)

In [80]:
# scaling the age and fare column
from sklearn.preprocessing import StandardScaler

In [81]:
scaler = StandardScaler()

In [83]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [84]:
X_train_scaled

array([[-1.61413602,  0.7243102 ,  1.22920747, ..., -0.07868358,
         0.55744438,  0.81220297],
       [-0.40055118,  0.7243102 , -0.50350514, ..., -0.37714494,
         0.55744438,  0.81220297],
       [ 0.81303367,  0.7243102 ,  0.18957991, ..., -0.47486697,
         0.55744438,  0.81220297],
       ...,
       [ 0.81303367,  0.7243102 ,  0.88266495, ..., -0.35580399,
         0.55744438, -1.23121934],
       [-1.61413602, -1.38062393, -1.19659018, ...,  1.68320121,
         0.55744438, -1.23121934],
       [-1.61413602,  0.7243102 , -0.65752403, ...,  0.86074761,
         0.55744438, -1.23121934]], shape=(712, 8))

In [91]:
# baseline model
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

In [92]:
model_lr = LogisticRegression()

In [93]:
model_lr.fit(X_train,y_train)

LogisticRegression()

In [94]:
y_pred_lr = model_lr.predict(X_test)

In [95]:
y_pred_lr

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [96]:
# eavluate model
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [97]:
accuracy = accuracy_score(y_test,y_pred_lr)

In [98]:
accuracy

0.8044692737430168

In [101]:
# KNearestNeighbors
from sklearn.neighbors import KNeighborsClassifier

In [109]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [110]:
model_knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [111]:
y_pred_knn = model_knn.predict(X_test_scaled)

In [112]:
y_pred_knn

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0])

In [113]:
# evaluate model
accuracy = accuracy_score(y_test,y_pred_knn)

In [114]:
accuracy

0.8212290502793296

In [115]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB

In [116]:
model_nb = GaussianNB()

In [117]:
model_nb.fit(X_train,y_train)

GaussianNB()

In [118]:
y_pred_nb = model_nb.predict(X_test)

In [119]:
y_pred_nb

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [120]:
# evaluate model
accuracy = accuracy_score(y_test,y_pred_nb)

In [121]:
accuracy

0.776536312849162

In [122]:
# Support Vector Machine
from sklearn.svm import SVC

In [123]:
model_svm = SVC()

In [124]:
model_svm.fit(X_train_scaled,y_train)

SVC()

In [125]:
y_pred_svm = model_svm.predict(X_test_scaled)

In [126]:
y_pred_svm

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0])

In [128]:
# evaluate model
accuracy = accuracy_score(y_test,y_pred_svm)

In [129]:
accuracy

0.8100558659217877

In [130]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

In [138]:
model_dt = DecisionTreeClassifier(random_state=42)

In [139]:
model_dt.fit(X_train_scaled,y_train)

DecisionTreeClassifier(random_state=42)

In [140]:
y_pred_dt = model_dt.predict(X_test_scaled)

In [141]:
y_pred_dt

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1])

In [142]:
# evaluate model
accuracy = accuracy_score(y_test,y_pred_dt)

In [143]:
accuracy

0.6312849162011173

In [144]:
# cross validation
from sklearn.model_selection import GridSearchCV

In [154]:
param_grid = {
    'n_neighbors':[1,3,5,7,9,11,13,19],
    'weights':['uniform','distance'],
    'metric':['euclidean','manhattan'],
    'p':[1,2]
}

knn = KNeighborsClassifier()

In [155]:
grid = GridSearchCV(
    estimator=knn,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [156]:
grid.fit(X_train_scaled,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [1, 3, 5, 7, 9, 11, 13, 19],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [157]:
print("Best parameters: ",grid.best_params_)
print("Best Accuracy : ",grid.best_score_)

Best parameters:  {'metric': 'euclidean', 'n_neighbors': 13, 'p': 1, 'weights': 'uniform'}
Best Accuracy :  0.8202206244459767

In [158]:
# applying random forest
from sklearn.ensemble import RandomForestClassifier

In [167]:
model_rf = RandomForestClassifier(random_state=42)

In [168]:
model_rf.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [169]:
y_pred_rf = model_rf.predict(X_test)

In [170]:
y_pred_rf

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 1])

In [171]:
accuracy = accuracy_score(y_test,y_pred_rf)

In [172]:
accuracy

0.8156424581005587

In [175]:
# hyperparameter tunning
param_grid = {
    'n_estimators':[100,200,300],
    'max_depth':[None,5,10,15],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,4],
    'max_features':['sqrt','log2']
}

grid = GridSearchCV(
    model_rf,
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [None, 5, 10, 15],
                         'max_features': ['sqrt', 'log2'],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy')

In [176]:
print("Best parameters: ",grid.best_params_)
print("Best Accuracy : ",grid.best_score_)

Best parameters:  {'max_depth': 5, 'max_features': 'log2', 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 100}
Best Accuracy :  0.8342263370432385

In [177]:
# Gradient Boosting
from sklearn.ensemble import GradientBoostingClassifier
model_gb = GradientBoostingClassifier(random_state=42)
model_gb.fit(X_train,y_train)
y_pred_gb = model_gb.predict(X_test)
print(accuracy_score(y_test,y_pred_gb))

0.8156424581005587

In [178]:
# hyper parameter tunning
param_grid = {
    'n_estimators':[100,200],
    'learning_rate':[0.01,0.05,0.1],
    'max_depth':[3,4,5],
    'subsample':[0.8,1.0]
}

In [179]:
grid = GridSearchCV(
    model_gb,
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(random_state=42),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.05, 0.1],
                         'max_depth': [3, 4, 5], 'n_estimators': [100, 200],
                         'subsample': [0.8, 1.0]},
             scoring='accuracy')

In [180]:
print("Best parameters: ",grid.best_params_)
print("Best Accuracy : ",grid.best_score_)

Best parameters:  {'learning_rate': 0.01, 'max_depth': 4, 'n_estimators': 200, 'subsample': 0.8}
Best Accuracy :  0.8272037821333595

In [181]:
# xgboost
from xgboost import XGBClassifier

In [182]:
xgb = XGBClassifier(random_state=42,eval_metric='logloss')

In [183]:
xgb.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [185]:
y_pred = xgb.predict(X_test)

In [186]:
print(accuracy_score(y_test,y_pred))

0.7877094972067039

In [188]:
param_grid = {
    'n_estimators':[100,200,300],
    'learning_rate':[0.01,0.05,0.1],
    'max_depth':[3,4,5],
    'subsample':[0.8,1.0],
    'colsample_bytree':[0.8,1.0]
}

grid = GridSearchCV(
    xgb,
    param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False,
                                     eval_metric='logloss', feature_types=None,
                                     feature_weights=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraint...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'colsample_bytree': [0.8, 1.0],
                         'learning_rate': [0.01, 0.05, 0.1],
                         'max_depth': [3, 4, 5],
                         'n_estimators': [100, 200, 300],
                         'subsample': [0.8, 1.0]},
             scoring='accuracy')

In [189]:
print("Best parameters: ",grid.best_params_)
print("Best Accuracy : ",grid.best_score_)

Best parameters:  {'colsample_bytree': 0.8, 'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 300, 'subsample': 0.8}
Best Accuracy :  0.8384615384615385

In [190]:
import joblib
joblib.dump(xgb,"titanic_model.pkl")

['titanic_model.pkl']

In [191]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embark_town', 'alone'],
      dtype='str')

In [192]:
X_train.columns

Index(['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embark_town',
       'alone'],
      dtype='str')